### ISSUE TITLE
Crash issue while afk.

### ISSUE THREAD

**Issue by sicklyFoxJay** [P3pp3rF1y/SophisticatedCore#249]
Crash issue while afk. Double chests textures start to mismatch, then game crashes with exit code 1. Not sure if the issue is directly with Sophisticated core, or with the mods that require it. Seems to not have the issue in single player.
[crash-2024-08-04_03.06.39-client.txt](https://github.com/user-attachments/files/16486853/crash-2024-08-04_03.06.39-client.txt)

**Comment by P3pp3rF1y** [comment]
Some mod seems to be able to put `CobbledexItem` item into upgrade slot at least on client side. No idea how exactly that could have happened because there are multiple protections against that but it did happen. You will need to figure out what mod is doing that, but there's basically nothing I can do about that.
