### ISSUE TITLE
[Bug]: Tabs don't stay rendered.

### ISSUE THREAD

**Issue by SpokenWig620933** [P3pp3rF1y/SophisticatedCore#67]
On the latest version of core I'm having issues with backpacks where the tap, such as a crafting tab, will "close" itself when I reopen a backpack, regardless of my tab setting, and it will disappear occasionally when I try to move any items in the backpack or when I click an item in the tab.

**Comment by SpokenWig620933** [comment]
The problem still occurs with 1.18.2-0.5.36.199

https://user-images.githubusercontent.com/49125888/209212699-26be5813-ade3-41e1-aef3-882bea2c0449.mp4

**Comment by P3pp3rF1y** [comment]
I should have this fixed with the next version. 

Still a little bit curious about what is causing that in your case as the bug would only happen when the full inventory is synchronized to the client and that by default only happens on open or on something like taking item from jei and putting it in the backpack. So there must be something in your pack that forces this to happen on a simple item pickup which is not ideal as it means a lot of data going from server to client on every slot change it seems.

**Comment by SpokenWig620933** [comment]
I can send you my pack if you need to look at what's happening.
Everything in my backpack shouldn't cause any updates besides the create saw texture being animated. Tho it works just fine in core 1.18.2-5.32.179

**Comment by P3pp3rF1y** [comment]
I don't really have time to debug what's happening in the pack - this all relates to the synchronization of the number of slots from server to the client where under normal circumstances it would only trigger this code on the first load hence why I added it there. Now I am fixing this closing of tabs by reloading that control only if the number of slots has changed, but not in any other case when all the slots are synchronized like they seem in your case.

**Comment by SpokenWig620933** [comment]
https://user-images.githubusercontent.com/49125888/210480425-fceb20ed-577c-4528-9c5a-aeb6cc0f5ffb.mp4

I did a quick test with only Sophisticated Backpacks/Core with forge-1.18.2-40.2.0.
The Tabs don't stay open still. I do not know what caused the tab to disappear when moving items though, possibly Create's texture rendering (Though that doesn't explain why it worked in a previous version of Sophisticated Backpacks).

Core -> 0.5.36.199
Backpacks -> 3.18.40.773

**Comment by P3pp3rF1y** [comment]
This is fixed in the latest version on curseforge
