### ISSUE TITLE
Game crashing at world creation

### ISSUE THREAD

**Issue by Pandaw15** [P3pp3rF1y/SophisticatedCore#76]
Hi ! So as several issues here, I have a problem with Sophisticated Core in 1.19.2 (SC version 0.5.38.203) where the game starts but crashes when clicking on Singleplayer and as it tries to prepare for world creation. I suspect this is from a config file, so I tried deleting it several times but it doesn't work; might be a forge issue with the mod and how the configs work ?

Here's the crash log so you can see for yourself: https://pastebin.com/8KXCYn5Z

**Comment by P3pp3rF1y** [comment]
What I can tell you about this is that it seems curseforge launcher is blocking config files for some reason and then it crashes the game when a mod writes something to config which is the case here. Switching to different launcher should fix it.

Let me know if that doesn't do the trick, otherwise I will just close.

**Comment by iobiarg** [comment]
Same happens to me, 
Based on the provided crash log, it appears that the mod causing the crash is "SophisticatedCore". The error seems to originate from the "net.p3pp3rf1y.sophisticatedcore" package and is related to a configuration setting for enabling/disabling items. Specifically, the error occurs when the mod tries to save changes to the configuration file, resulting in a "ConfigWriter" exception being thrown.

Is there going to be a fix on the mod side creator?

**Comment by P3pp3rF1y** [comment]
> 

could you share your crash log?

**Comment by iobiarg** [comment]
Sure, I removed the mod and forgot to remove the configs and the crash happened again. Once I removed also the configs, the game would work just fine.

I use a shit ton of mods, but the text I put there wasn't created by me because I know nothing about coding. A tool read the crash log and gave me that feedback.

Hugs! 

[crash-2023-03-29_01.23.20-client.txt](https://github.com/P3pp3rF1y/SophisticatedCore/files/11107582/crash-2023-03-29_01.23.20-client.txt)

**Comment by P3pp3rF1y** [comment]
@iobiarg what launcher do you use? is it curseforge?

**Comment by iobiarg** [comment]
It's called TLauncher-2.75-Installer-0.6.9.v2
I've been using it for many years, in the past, I used the TeamExtreme one. 
Do you know of any other that works "offline" or without a MC account (third-world problem, we can't afford official games)

BTW, I saw a new file from the mod, are you testing this?

**Comment by P3pp3rF1y** [comment]
I don't support piracy especially for game so cheap as Minecraft so I am going to forget about your report @iobiarg

**Comment by iobiarg** [comment]
Okey, it's fine, I get it. Won't argue the decision.
But just for you to know, ppl from countries with devaluated coins like mine, are unable to afford games in foreign coins. The cost of the game without taking into account the fact that many have the purchase of dollars forbidden by the government, so the price we pay for dollars is not what you see in "conversion tables online", (is actually 70% higher), and not taking into account the taxes our country add over anything bought abroad (60%), it more than what a middle-class person uses for eating several days...

So, you are right about not supporting piracy. But before adding a subjective adjective such as "cheap" to sth, you should know that that's not the case for ppl leaving in totally different realities from North America, Europe, or other places where the economy is not choking ppl. 

Thanks for the willingness to help before you knew this. Hope you keep developing.

Hugs.

PD: I promise that if I ever post an issue here again, it will be once I'm able to afford the official game.

**Comment by P3pp3rF1y** [comment]
closing
